### ISSUE TITLE
Remove ITKDeprecated (and ITKV3Compatibility from list of ITK components

### ISSUE THREAD

**Issue by jcfr** [BRAINSia/BRAINSTools#154]
To follow up with 13969f35, I would suggest to remove the corresponding ITK components.

See https://github.com/BRAINSia/BRAINSTools/search?utf8=%E2%9C%93&q=ITKDeprecated
and https://github.com/BRAINSia/BRAINSTools/search?utf8=%E2%9C%93&q=ITKV3Compatibility+

**Comment by hjmjohnson** [comment]
This was completed during NAMIC project week
