### ISSUE TITLE
Fix Failing Test for BRAINSABC

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/BRAINSTools#176]
Alex,  

Please do the main work for this, and then send the email to @aghayoor  (ali-ghayoor@uiowa.edu)

The BRAINSABC test that is failing regression.

This is the test that is failing:
http://testing.psychiatry.uiowa.edu/CDash/testDetails.php?test=765554&build=38026

After review, I have determined that this test result is good.

Please make an e-mail to @aghayoor with the instructions necessary to fix this failing test.

Hans

===========================
HINTS:
%man md5
% cd BRAINSTools/TestData;  cat scan1T1.nii.gz.md5
% cat BRAINSTools/CMake/ExternalData.cmake
% printenv |grep OBJE
ExternalData_OBJECT_STORES=/Shared/sinapse/sharedopt/CommonCDashScripts/ExternalData/Objects

**Comment by hjmjohnson** [comment]
@aghayoor Ali please close this if it is no longer relavant.

**Comment by aghayoor** [comment]
@hjmjohnson : The "http://testing.psychiatry.uiowa.edu" link is not working anymore, so I cannot see which test exactly the given link points to. However, BRAINSABCSmallTest that is submitted to new dashboard is passing successfully before and after adding pure plugs mask.
