### ISSUE TITLE
ROIAuto is NOT equivalent to manual cropping to non-zero part

### ISSUE THREAD

**Issue by dzenanz** [BRAINSia/BRAINSTools#179]
Executing BRAINSFit with ROIAuto set to ON is not equivalent to running BRAINSROIAuto and then feeding cropped images into BRAINSFit. I was using useMomentsAlign in both cases.

[Pyhton source code fragment exemplifying the issue](https://gist.github.com/dzenanz/bec172bd4af1f1527cf1)
[Fixed image](https://drive.google.com/file/d/0ByGZiVpMK4MXMEhJeW9OelhweVk/view?usp=sharing)
[Moving image](https://drive.google.com/file/d/0ByGZiVpMK4MXOHhac2loOEV4NUE/view?usp=sharing)
[Discussion (Context)](http://slicer-users.65878.n3.nabble.com/Tough-cases-for-automatic-registration-tp4028581p4028599.html)

**Comment by hjmjohnson** [comment]
Correct.  The ROIAuto flag does not crop the data internally in BRAINSFit.  It only identifies the mask. 

The cropping option of the stand alone BRAINSROIAuto is for different purpose.

**Comment by hjmjohnson** [comment]
It is unclear what the desired behavior or change request is for this case.
