### ISSUE TITLE
DWIConvert Images inverted.

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/BRAINSTools#185]
DWIConvert loading images upside down.

Ali: We need a test that fails with the current code, and succeeds when the BUG regarding upside down data is resolved.

Here is a test patch to try.  I did not test it, I only made changes based on a guess to the problem. The code that you isolated changed behavior due to refactoring when adding the "else" component. of the if statement.  

https://github.com/BRAINSia/BRAINSTools/tree/DWIConvertFixAttempt

**Comment by hjmjohnson** [comment]
Ali,
 It looks like the file DWICompare.cpp needs to have more tests to ensure that the origin/spacing/direction cosigns are maintained consistent to the tests.  

NOTE:  It appears that DWICompare.cpp is only checking gradient directions.  It does not seem to be checking intensity information or spacing, or direction.

**Comment by aghayoor** [comment]
Hans, 

I think your changes (https://github.com/BRAINSia/BRAINSTools/commit/e766bd48454b43518d758cc0d668c66b65074931) won't address the current issue.

I narrowed down the problem to the mismatch between image0Origin and image1Origin in DWIConverter.h. Sorry that I had to leave working on this because of a big load of reading materials. Hopefully, I can spare 2 hours tomorrow to continue working on this issue and fixing the bug.

Thanks,
Ali

**Comment by hjmjohnson** [comment]
@aghayoor I added new patches to both the master branch, and the DWIConvertFixAttempt branch.

My tests are now failing, some of them due to the bug, some of them due to a need for tolerance int the tests.

Please update the "DWIConvertFixAttempt" patch to allow for small tolerance in spacing, origin, direction so that the values are close (using itk::Math::FloatDifferenceULP to make comparisons).

All tests need to be made to pass.

Hans

**Comment by aghayoor** [comment]
@hjmjohnson A test message from Github!

**Comment by hjmjohnson** [comment]
@aghayoor   What is the status of this work?

**Comment by aghayoor** [comment]
This issue is fixed:
https://github.com/BRAINSia/BRAINSTools/commit/66703244984c0023d01f2ed6bda0d9ca5ea4ea6d
https://github.com/BRAINSia/BRAINSTools/commit/5fecb44ab59c335e3093a0ab477d63d837975512
