### ISSUE TITLE
ConvertBetweenFileFormats / DWIConvert: nrrd to nii -> Images squashed

### ISSUE THREAD

**Issue by gblokland** [BRAINSia/BRAINSTools#186]
Hi,
I'm using ConvertBetweenFileFormats to convert T1-weighted scans/brain masks from nrrd to nii. However, after installing the latest version of BRAINSTools a strange resampling happens when I convert to nii: The brain in squashed in one of the directions (L-R or S-I) (One plane looks normal). I also tried to use DWIConvert, but the same thing happens. With the older version of BRAINSTools (installed about 9 months ago) I did not have this issue. Does anyone have any ideas as to what could be going on?

Thanks,
Gabriëlla

**Comment by dmwelch** [comment]
Are you building off the master branch?  We've been working on some issues with NRRD conversion, so you may be building a broken commit.  (I know and we're sorry. :disappointed: )  

Can you paste the NRRD header from your file and we'll see what we can do?  ITK's support for 4D NRRD is still buggy so I suspect that your image isn't indexed the way itk::NrrdIO is expecting...

**Comment by gblokland** [comment]
Hi David,

This is what I ran to build BRAINSTools:

	git clone https://github.com/BRAINSia/BRAINSTools.git
	mkdir BRAINSTools-build && cd BRAINSTools-build
	CC=/usr/bin/gcc \
	CXX=/usr/bin/g++ \
	ccmake ../BRAINSTools \
	-DUSE_BRAINSFit:BOOL=ON \
	-DUSE_BRAINSConstellationDetector:BOOL=ON \
	-DUSE_BRAINSABC:BOOL=ON \
        -DUSE_ConvertBetweenFileFormats:BOOL=ON \
	-DPYTHON_EXECUTABLE:PATH=/usr/pubsw/packages/python/epd/bin/python2.7 \
	-DPYTHON_LIBRARY:PATH=/usr/pubsw/packages/python/epd/lib \
	-DPYTHON_INCLUDE_DIR:PATH=/usr/pubsw/packages/python/epd/include
	make -j 1 -k
	make

This is the nrrd header:
$ ~/opt/BRAINSTools-build/bin/unu head T1.nrrd
NRRD0004
# Complete NRRD file format specification at:
# http://teem.sourceforge.net/nrrd/format.html
type: float
dimension: 3
space: left-posterior-superior
sizes: 256 256 124
space directions: (0.78130000829696655,0,0) (0,-0.7813000079331448,2.3843400402067491e-05) (0,4.5776399907992928e-05,1.499999999301507)
kinds: domain domain domain
endian: little
encoding: gzip
space origin: (-99.609397888183594,70.204505920410156,-81.131378173828125)


Thanks very much for your help.

Best wishes,
Gabriëlla Blokland

**Comment by dmwelch** [comment]
Gabriella, 

Sorry for the delay - a few questions to give me more info:
1) what version of gcc do you have?
2) what OS are you running?

Also, can you send one of your NRRD files that your having the issue with?

Dave

**Comment by gblokland** [comment]
Hi David,

gcc version: gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

OS: CentOS release 6.6 (Final)

Attached is one of the NRRD files we would like to convert back to nifti.

Thanks!
Gabriëlla

**Comment by dmwelch** [comment]
I don't see an attachment.  Can you email me it directly (we'll keep discussion here)?

**Comment by hjmjohnson** [comment]
We will need test data in order to debug this.

**Comment by hjmjohnson** [comment]
Without test data, there is no way for us to proceed efficiently.

**Comment by gblokland** [comment]
Hi,

I sent test data before. Attaching it to the github message didn’t work so I sent the files directly to David Welch.

Best wishes,
Gabriëlla
----------------------------------------------------------------------------------------------------------------------------------
Gabriëlla A. M. Blokland, Ph.D.
Postdoctoral Research Fellow

Petryshen Laboratory
Psychiatric and Neurodevelopmental Genetics Unit
Center for Human Genetic Research & Department of Psychiatry
Massachusetts General Hospital | Harvard Medical School
185 Cambridge Street, Boston MA 02114
Phone: +1 617 643 9301  |  Fax: +1 617 726 0830  |  E-mail: gblokland@mgh.harvard.edu<mailto:gblokland@mgh.harvard.edu>

On 20 Jul 2015, at 10:09 am, Hans Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Without test data, there is no way for us to proceed efficiently.

—
Reply to this email directly or view it on GitHub<https://github.com/BRAINSia/BRAINSTools/issues/186#issuecomment-122897178>.



The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by dmwelch** [comment]
Forwarding the test data to Hans

**Comment by hjmjohnson** [comment]
???
I just downloaded the test data, ran:
~/src/NEP-11/bin/ConvertBetweenFileFormats mabs_brainmask.nrrd mabs_brainmask.nii

Loaded both data sets in Slicer3D, and they were identical.   We have not 

The last non-documentation change to the code was in 2012.

Hans
