### ISSUE TITLE
CXX_HAS_DISABLE_OPTIMIZATION_FLAG failed

### ISSUE THREAD

**Issue by mlmia** [BRAINSia/BRAINSTools#191]
When we compile BRAINSTools on Scientific Linux release 7.1 (Nitrogen), we receive the following error (see below) - any help would be much appreciate.

---------------------------------------------------------------------------------------------------------------

Performing C++ SOURCE FILE Test CXX_HAS_DISABLE_OPTIMIZATION_FLAG failed with the following output:
Change Dir: /usr/local/toolboxes/BRAINSTools/BTLib/BRAINSTools-build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTryCompileExec1080464923/fast"
gmake[3]: Entering directory `/usr/local/toolboxes/BRAINSTools/BTLib/BRAINSTools-build/CMakeFiles/CMakeTmp'
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec1080464923.dir/build.make CMakeFiles/cmTryCompileExec1080464923.dir/build
gmake[4]: Entering directory `/usr/local/toolboxes/BRAINSTools/BTLib/BRAINSTools-build/CMakeFiles/CMakeTmp'
/usr/local/toolboxes/cmake/cmake-3.2.2-Linux-x86_64/bin/cmake -E cmake_progress_report /usr/local/toolboxes/BRAINSTools/BTLib/BRAINSTool$
Building CXX object CMakeFiles/cmTryCompileExec1080464923.dir/src.cxx.o
/usr/bin/c++    -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wsha$
/usr/local/toolboxes/BRAINSTools/BTLib/BRAINSTools-build/CMakeFiles/CMakeTmp/src.cxx:1:1: error: expected unqualified-id before ‘-’ token
 -O0
 ^
gmake[4]: *** [CMakeFiles/cmTryCompileExec1080464923.dir/src.cxx.o] Error 1
gmake[4]: Leaving directory `/usr/local/toolboxes/BRAINSTools/BTLib/BRAINSTools-build/CMakeFiles/CMakeTmp'
gmake[3]: *** [cmTryCompileExec1080464923/fast] Error 2
gmake[3]: Leaving directory `/usr/local/toolboxes/BRAINSTools/BTLib/BRAINSTools-build/CMakeFiles/CMakeTmp'

Source file was:
-O0

**Comment by dmwelch** [comment]
Is this a test failure or a build failure? It's not clear from your report what test is failing.  Please provide:
1. your command line
2. the contents of `/usr/local/toolboxes/CMakeCache.txt`
3. the location of the source directory (i.e. was this an "in-source build" or not?)
4. Name of failing test, if applicable.

Cheers!

**Comment by hjmjohnson** [comment]
We have been unable to reproduce this error, so we can not fix. Please re-open if futher information can be provided.
