### ISSUE TITLE
unrecognized command line option "-Wno-long-double"

### ISSUE THREAD

**Issue by gblokland** [BRAINSia/BRAINSTools#195]
Hi,

We're trying to install BRAINSTools on Scientific Linux release 6.6 (Carbon), with:
gcc (and g++) version: gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11).

Code run:

git clone https://github.com/BRAINSia/BRAINSTools.git
mkdir BRAINSTools-build && cd BRAINSTools-build
CC=/usr/bin/gcc \
CXX=/usr/bin/g++ \
ccmake ../BRAINSTools \
	-DUSE_BRAINSFit:BOOL=ON \
	-DUSE_BRAINSConstellationDetector:BOOL=ON \
	-DUSE_BRAINSABC:BOOL=ON \
        -DUSE_ConvertBetweenFileFormats:BOOL=ON \
        -DUSE_BRAINSSurfaceTools:BOOL=OFF \
	-DPYTHON_EXECUTABLE:PATH=/usr/pubsw/packages/python/epd/bin/python2.7 \
	-DPYTHON_LIBRARY:PATH=/usr/pubsw/packages/python/epd/lib \
	-DPYTHON_INCLUDE_DIR:PATH=/usr/pubsw/packages/python/epd/include
	make -j 1 -k
	make

We are getting the following error:

[ 98%] Building CXX object Modules/IO/TransformBase/src/CMakeFiles/ITKIOTransformBase.dir/itkTransformFileWriterSpecializations.cxx.o
/opt/BRAINSTools-build/ITKv4/Modules/IO/TransformBase/src/itkTransformFileWriterSpecializations.cxx:176: error: using ‘typename’ outside of template
/opt/BRAINSTools-build/ITKv4/Modules/IO/TransformBase/src/itkTransformFileWriterSpecializations.cxx:177: error: using ‘typename’ outside of template
/opt/BRAINSTools-build/ITKv4/Modules/IO/TransformBase/src/itkTransformFileWriterSpecializations.cxx:184: error: using ‘typename’ outside of template
/opt/BRAINSTools-build/ITKv4/Modules/IO/TransformBase/src/itkTransformFileWriterSpecializations.cxx:185: error: using ‘typename’ outside of template
cc1plus: warning: unrecognized command line option "-Wno-long-double"
make[5]: *** [Modules/IO/TransformBase/src/CMakeFiles/ITKIOTransformBase.dir/itkTransformFileWriterSpecializations.cxx.o] Error 1
make[4]: *** [Modules/IO/TransformBase/src/CMakeFiles/ITKIOTransformBase.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ITKv4-prefix/src/ITKv4-stamp/ITKv4-build] Error 2
make[1]: *** [CMakeFiles/ITKv4.dir/all] Error 2
make: *** [all] Error 2

After some searching online, I came across some references saying that the -Wno-long-double argument is no longer needed in most cases. I found a source saying that the autoconf scripts should be running a test to determine whether or not gcc accepts the -Wno-long-double argument, so we tried adding these two lines to the file CMakeCache.txt in the BRAINSTools-build directory (not at all sure if these settings make sense):

//Test C_HAS_WARNING-Wno-long-double
C_HAS_WARNING-Wno-long-double:INTERNAL=1

followed by running just ‘make’ from that directory, but got the same error.

Another source was saying it might be the gcc version, and that some (older) versions of the compiler gcc don’t accept this argument (current version is 4.8.X), but the gcc version is exactly the same as on another system we successfully installed BRAINSTools on, so I don't think that is it.

Do you have ideas as to how we might be able to fix this issue?

Thanks very much in advance.

Gabriëlla

**Comment by hjmjohnson** [comment]
Gabriella,

You have the wrong message regarding why your builds are failing.  The correct error message is:

/opt/BRAINSTools-build/ITKv4/Modules/IO/TransformBase/src/itkTransformFileWriterSpecializations.cxx:176: error: using ‘typename’ outside of template

We fixed this last week, and the newest release of BRAINSTools should now work.

Hans
=========================================
Hans J. Johnson
hans.j.johnson@gmail.com

**Comment by hjmjohnson** [comment]
Was fixed in this release when building stand alone.

https://github.com/BRAINSia/BRAINSTools/commit/52302842a7e16813266ee86fc2840b0615bb7ced
