### ISSUE TITLE
Version number written in log file of DWIConvert

### ISSUE THREAD

**Issue by fbudin69500** [BRAINSia/BRAINSTools#201]
The version of DWIConvert that is written in the log file is hard-coded in the source file of DWIConvert. The version number of DWIConvert has been changed from 1.0 to 4.4.0 but the version number that is hard-coded in DWIConvert.cxx has not been updated.

https://github.com/BRAINSia/BRAINSTools/blob/master/DWIConvert/DWIConvert.cxx#L471-L475

**Comment by hjmjohnson** [comment]
@fbudin69500 Thank you.  We will try to address this soon.

Hans

**Comment by aghayoor** [comment]
This is fixed:
https://github.com/BRAINSia/BRAINSTools/commit/7f0daee67c442e5eb6af01c042d942b4f5be26d4
