### ISSUE TITLE
Registration deconverges

### ISSUE THREAD

**Issue by dzenanz** [BRAINSia/BRAINSTools#212]
Invoking the registration (from e.g. nightly build of Slicer) with many parameter combinations (including the defaults) with below inputs (fixed and moving images and initial registration transform which is very close) results in registration veering off course. This should not happen. Both images together are 1 megabyte.

https://dl.dropboxusercontent.com/u/48665006/bugFixed.nrrd
https://dl.dropboxusercontent.com/u/48665006/bugMoving.nrrd
https://dl.dropboxusercontent.com/u/48665006/bugInitial.txt

**Comment by hjmjohnson** [comment]
We will need registration parameters and the command line that you used in order to replicate the problem.

**Comment by dzenanz** [comment]
General Registration (BRAINS) command line: 

slicer:000007FEDE9CB5E0 --processinformationaddress 000000001219F908 --fixedVolume slicer:0000000003D2FFD0#vtkMRMLScalarVolumeNode4 --movingVolume slicer:0000000003D2FFD0#vtkMRMLScalarVolumeNode2 --linearTransform C:/Users/Dzenan/AppData/Local/Temp/Slicer/GCGA_vtkMRMLLinearTransformNodeF.h5 --initialTransform C:/Users/Dzenan/AppData/Local/Temp/Slicer/GCGA_vtkMRMLLinearTransformNodeE.h5 --initializeTransformMode Off --samplingPercentage 0.002 --useRigid --splineGridSize 14,10,12 --numberOfIterations 1500 --maskProcessingMode NOMASK --outputVolumePixelType float --backgroundFillValue 0 --maskInferiorCutOffFromCenter 1000 --interpolationMode Linear --minimumStepLength 0.001 --translationScale 1000 --reproportionScale 1 --skewScale 1 --maxBSplineDisplacement 0 --numberOfHistogramBins 50 --numberOfMatchPoints 10 --numberOfSamples 0 --fixedVolumeTimeIndex 0 --movingVolumeTimeIndex 0 --medianFilterSize 0,0,0 --removeIntensityOutliers 0 --useCachingOfBSplineWeightsMode ON --useExplicitPDFDerivativesMode AUTO --ROIAutoDilateSize 0 --ROIAutoClosingSize 9 --relaxationFactor 0.5 --maximumStepLength 0.05 --failureExitCode -1 --numberOfThreads -1 --forceMINumberOfThreads -1 --debugLevel 0 --costFunctionConvergenceFactor 2e+013 --projectedGradientTolerance 1e-005 --maximumNumberOfEvaluations 900 --maximumNumberOfCorrections 25 --metricSamplingStrategy Random --costMetric MMI --metricSeed 21474836

**Comment by jcfr** [comment]
@dzenanz If within Slicer Module settings, you set "Prefer CLI executable", the command line logged will contain file paths instead of memory references like `slicer:000007FEDE9CB5E0`, that should help debugging.

**Comment by dzenanz** [comment]
"C:/Program Files/Slicer 4.4.0/lib/Slicer-4.4/cli-modules/BRAINSFit.exe" --fixedVolume C:/bugFixed.nrrd --movingVolume C:/bugMoving.nrrd --linearTransform C:/resultTransform.h5 --initialTransform C:/bugInitial.txt --initializeTransformMode Off --samplingPercentage 0.002 --useRigid --splineGridSize 14,10,12 --numberOfIterations 1500 --maskProcessingMode NOMASK --outputVolumePixelType float --backgroundFillValue 0 --maskInferiorCutOffFromCenter 1000 --interpolationMode Linear --minimumStepLength 0.001 --translationScale 1000 --reproportionScale 1 --skewScale 1 --maxBSplineDisplacement 0 --numberOfHistogramBins 50 --numberOfMatchPoints 10 --numberOfSamples 0 --fixedVolumeTimeIndex 0 --movingVolumeTimeIndex 0 --medianFilterSize 0,0,0 --removeIntensityOutliers 0 --useCachingOfBSplineWeightsMode ON --useExplicitPDFDerivativesMode AUTO --ROIAutoDilateSize 0 --ROIAutoClosingSize 9 --relaxationFactor 0.5 --maximumStepLength 0.05 --failureExitCode -1 --numberOfThreads -1 --forceMINumberOfThreads -1 --debugLevel 0 --costFunctionConvergenceFactor 2e+013 --projectedGradientTolerance 1e-005 --maximumNumberOfEvaluations 900 --maximumNumberOfCorrections 25 --metricSamplingStrategy Random --costMetric MMI --metricSeed 21474836

**Comment by hjmjohnson** [comment]
@dzenanz 

Can you please share the input files (images and transforms) so that we can replicate the problem in our environment?

Thanks,
Hans

**Comment by dzenanz** [comment]
I did, in the first post. Here are the links again:
https://dl.dropboxusercontent.com/u/48665006/bugFixed.nrrd
https://dl.dropboxusercontent.com/u/48665006/bugMoving.nrrd
https://dl.dropboxusercontent.com/u/48665006/bugInitial.txt

**Comment by aghayoor** [comment]
@dzenanz 

When running a registration process, the transforms should be ordered appropriately for the processing i.e. transforms go from low dimensional to high dimensional. See following ordering for BRAINSFit:
Rigid=1, ScaleVersor3D=2, ScaleSkewVersor3D=3, Affine=4, and (BSpline or SyN)=5

In your example, your initial transform is an "affine" transform; however, you run only one rigid step at top of it.
To get correct registration results, your registration should begin with a transformation that has equal or higher dimension than your initial transform. For example in your case, you should start registration with an affine stage or higher.
Let me know if you have more questions about this.

Best,
Ali

**Comment by dzenanz** [comment]
The initial transform is a rigid transform (there is no scaling and no skew present in the transform). However when saving it to disk, Slicer always writes it as affine. In fact, Slicer does not have a simpler transform type than "Linear" - ITK's affine.

**Comment by aghayoor** [comment]
What is important here is the dimension and the type of your initial transform, even though it may just do orientation and translation.
If you want to have only Rigid registration, use one of the "Initialize Transform Mode" in BRAINS.
For example using "useGeometryAlign" mode provides acceptable initialization in your test case.

**Comment by hjmjohnson** [comment]
Based on Ali's description of the problem, I am assuming that your initial images do not initially overlap in physical space.  

(They may overlap in voxel space, but the origins/directions) cause them to be disjoint in physical space.  You would then need to give some initial transform to provide overlaping regions for registrations tosucceed..

**Comment by dzenanz** [comment]
What I was doing is register two downsampled images using rigid mode, and trying to pass the output transform as initialization to a higher resolution version of the same images to do rigid registration again. To my amazement, the second registration sometimes goes out of whack even if the first one finishes correctly. I guess what I was trying to do is not a supported use-case?

**Comment by hjmjohnson** [comment]
We do what you describe all the time.  I am assuming that you have identified an alternate solution and that this issue has been resolved by now.
