### ISSUE TITLE
COMPARE_GenusZeroImageFilter test output

### ISSUE THREAD

**Issue by ajjl** [BRAINSia/BRAINSTools#214]
@aghayoor @hjmjohnson 
This test passes on debian and mac:
http://my.cdash.org/testDetails.php?test=21303298&build=835882

but the output shows errors:
Error during write of {....}/BRAINSTools-build/BRAINSSurfaceTools/GenusZeroImageFilter/TEST_GenusZeroImageFilter.nii.gz.base.png
Error during write of {same path}/TEST_GenusZeroImageFilter.nii.gz.test.png

I'm not exactly sure whats wrong or how to fix it.

**Comment by hjmjohnson** [comment]
This error has not been successfully replicated.
