### ISSUE TITLE
Build fails on ANTs download step

### ISSUE THREAD

**Issue by pnlbwh** [BRAINSia/BRAINSTools#220]
Keep running into this error (see below), but sometimes it works, and I can't figure out why.
git diff `ExternalApplications/MALF/CMakeLists.txt` shows only trivial line ending or space removal changes for each line.  The ANTs repo is checked out as master, but in the instance that the build worked it was headless.

Any idea what's going on?

------
[ 64%] Performing download step (git clone) for 'ANTs'
Initialized empty Git repository in /tmp/BRAINSTools-build/ANTs/.git/
remote: Counting objects: 18669, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 18669 (delta 0), reused 0 (delta 0), pack-reused 18665
Receiving objects: 100% (18669/18669), 18.12 MiB | 889 KiB/s, done.
Resolving deltas: 100% (12506/12506), done.
error: You have local changes to 'ExternalApplications/MALF/CMakeLists.txt'; cannot switch branches.
CMake Error at ANTs-prefix/tmp/ANTs-gitclone.cmake:49 (message):
  Failed to checkout tag: '8a995a03548b4bc97c2b3c8be83f0e14e1be4688'

make[2]: *** [ANTs-prefix/src/ANTs-stamp/ANTs-download] Error 1
make[1]: *** [CMakeFiles/ANTs.dir/all] Error 2
make: *** [all] Error 2

**Comment by hjmjohnson** [comment]
Even trivial line changes are line changes.  

In order to do a git update, it is REQUIRED that you have no local changes (not even a single space change).

If you cd into the ANTs source code directory and type “git reset HEAD —hard” that should allow you to continue building.

Hans

**Comment by pnlbwh** [comment]
I had to set 'git config --global core.autocrlf false' before building so that the line endings aren't changed on checkout, thanks for the hint.
