### ISSUE TITLE
Place crashdump files in workflow base directory.

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/BRAINSTools#221]
A common problem with our batch processing is that crashdump files clutter up the script directory.  We fully expect many failed runs (due to using the all.q), and the large number of these crash files need to be constantly cleaned up.

Test and add something similar to the following so that the crash files goto the temporary cache directory that is easier to delete.

workflow.config['execution']['crashdump_dir'] = os.path.join(workflow.base_dir, workflow.name)

Hans

**Comment by reginakim** [comment]
Lucky, I just made my NamicExternal build on my OS X. ;)

Some quick search:
http://unix.stackexchange.com/questions/174817/finding-the-correct-tmp-dir-on-multiple-platforms

1. On OS X:

```
$echo $TMPDIR
$/var/folders/_c/r0pymxb95tqdc8c6xg60byfh015msc/T/
```

2. On Linux:

```
$ mktemp 
/tmp/tmp.5BO2YEjDgW
```

I will let you know once I start testing these.

Regina
