### ISSUE TITLE
DWIConvert alters bval/bvector values when run using command line

### ISSUE THREAD

**Issue by dtosun** [BRAINSia/BRAINSTools#226]
I have a similar issue: https://github.com/BRAINSia/BRAINSTools/issues/183

I just installed the latest Slicer release (4.5.0-1 for macosx).

If I run DWIConvert from the Slicer user interface to convert an nhdr/raw.gz image to a nifti image, it creates the bvec and bval files with correct entries but doesn't create a .nii image file.

Then if I use the command line to convert the nhdr/raw.gz image to a nii image, it creates the nii file properly but this time the values in the bvec and bval are totally off and looks totally random.

Here is the command I used:

Slicer.app/Contents/lib/Slicer-4.5/cli-modules/DWIConvert \
--inputVolume /path/to/input/Subject1.nhdr \
-o /path/to/output/Subject1.nii \
--outputBVectors /path/to/output/Subject1.bvec \
--outputBValues /path/to/output/Subject1.bval \
--conversionMode NrrdToFSL

Is there any particular flag or switch I should have used with the command line version?
Thanks

**Comment by ihnorton** [comment]
@dtosun:

> If I run DWIConvert from the Slicer user interface to convert an nhdr/raw.gz image to a nifti image, it creates the bvec and bval files with correct entries but doesn't create a .nii image file.

I agree this is confusing -- could you please open a separate issue about this?

> Then if I use the command line to convert the nhdr/raw.gz image to a nii image, it creates the nii file properly but this time the values in the bvec and bval are totally off and looks totally random.

It's a bit difficult to debug without more information (test data or at least a log of the DWIConvert output). However, I have coincidentally been working through such a comparison myself recently. In my (limited) test cases, the difference between dcm2nii and DWIConvert gradient directions is explained by the fact that dcm2nii/dcm2niix [rotates the gradients by the ImageOrientationPatient](https://github.com/neurolabusc/dcm2niix/blob/5bdb860c0fcd317bdec0916fa7d814812a309444/console/nii_dicom_batch.cpp#L260-L320), whereas DWIConvert does not.

**Comment by ihnorton** [comment]
> dcm2nii/dcm2niix rotates the gradients by the ImageOrientationPatient

i.e.:

```
julia> iops_raw = R"1\0\0\0\0.96547262605295\-0.2605045265296"
"1\\0\\0\\0\\0.96547262605295\\-0.2605045265296"

julia> iops = map(float, split(iops_raw, "\\"))
6-element Array{Float64,1}:
  1.0
  0.0
  0.0
  0.0
  0.965473
 -0.260505

julia> iops_mat = hcat(iops[1:3], iops[4:6], cross(iops[1:3], iops[4:6]))'
3x3 Array{Float64,2}:
  1.0  0.0        0.0
  0.0  0.965473  -0.260505
 -0.0  0.260505   0.965473

julia> grad1 = [0.70782137   0.00430414   -0.70637822] # copied from NHDR
1x3 Array{Float64,2}:
 0.707821  0.00430414  -0.706378

julia> iops_mat * grad1'
3x1 Array{Float64,2}:
  0.707821
  0.18817
 -0.680868
```

the output of the last step matches the first gradient in the bvec file for this dataset.

**Comment by dtosun** [comment]
We figured out the problem. in our nhdr header file, bvectors are listed with comma separation. once I replaced the commas with space, it worked fine. 

thanks for your response.
