### ISSUE TITLE
BRAINSFitTest_ROIBSpline Needs updated reference dataset

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/BRAINSTools#260]
@aghayoor   Please update the reference data set for BRAINSFitTest_ROIBSpline.  A recent improvement in ROI generation has caused improved results, so now we need updated baselines.

Please complete this ASAP.

Thank you.
hans

**Comment by aghayoor** [comment]
Fixed!
https://github.com/BRAINSia/BRAINSTools/commit/d3bc2210a6f8f66d637b256a83e74193519c6e9c
