### ISSUE TITLE
DWIConvert FSLtoNrrd with floating point NIfTI

### ISSUE THREAD

**Issue by ihnorton** [BRAINSia/BRAINSTools#261]
On the Slicer mailing list there is a [question about converting NIfTI DWI to NRRD](http://slicer-users.65878.n3.nabble.com/Change-in-scalar-type-of-NRRD-image-td4030122.html#a4030141) when the NIfTI voxel type is `float` (unclear whether it is "actually" float or apparent-float due to non-zero `scl_slope`). The resulting NRRD has `short` voxels, because the DWIConvert `PixelType` is hard-coded as `short`.

I've done some testing with "pathological" NIfTI files (`scl_slope` set such that the <s>resulting</s> rescaled values are either < 1 or > `typemax(Int16)`), and DWIConvert silently truncates these files to 0. This seems problematic given our target userbase.

- should DWIConvert support `float` as an output NRRD type? I think Slicer's tensor estimation will work fine with `float`-valued DWIs (it casts everything to `double` internally), but I don't know about the other tools.
- if not, I would suggest that DWIConvert should throw an error (and I can make a PR to that effect).

cc @ljod

[related note: apparently Philips scanners use the DICOM `RescaleSlope` tag incorrectly, as discussed on [comp.dicom via the gdcm wiki](http://gdcm.sourceforge.net/wiki/index.php/Modality_LUT#Rescale_slope_and_intercept_in_MR_datasets.2C_what_are_they_used_for.3F) and this recent [QIN paper](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3998685/). dcm2nii [includes this factor in the output NIfTI](https://github.com/neurolabusc/dcm2niix/blob/f02722822d8324046db1c1668317c12ef1e9a424/console/nii_dicom.cpp#L2858-L2867) for such Philips images]

**Comment by hjmjohnson** [comment]
Isaiah,

Thank you for the note.  I think it would be fine to have the ability to write out float.  I definitely think that it would be good to catch failure cases and give meaningful failure results.

I’d be happy to review a pull request and accept quickly if you can implement this.

Thank you,
Hans

**Comment by hjmjohnson** [comment]
Thank you for the bug fix.
