### ISSUE TITLE
Compile fails

### ISSUE THREAD

**Issue by pnlbwh** [BRAINSia/BRAINSTools#269]
I've been unable to build BRAINSTools in the last couple of weeks because of the error below.
The downloaded file (BRAINSTools-build/ITKv4-build/fftwd/src/fftw-3.3.4.tar.gz) is 0 bytes.

Scanning dependencies of target fftwd
[  0%] Creating directories for 'fftwd'
[  0%] Performing download step (download, verify and extract) for 'fftwd'
-- downloading...
     src='https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=2edab8c06b24feeb3b82bbb3ebf3e7b3&name=fftw-3.3.4.tar.gz'
     dst='/tmp/pnlutil/install-software/BRAINSTools-build/ITKv4-build/fftwd/src/fftw-3.3.4.tar.gz'
     timeout='none'
CMake Error at fftwd-stamp/download-fftwd.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/tmp/pnlutil/install-software/BRAINSTools-build/ITKv4-build/fftwd/src/fftw-3.3.4.tar.gz]
      expected hash: [2edab8c06b24feeb3b82bbb3ebf3e7b3]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]

**Comment by ihnorton** [comment]
Remove the file `/tmp/pnlutil/install-software/BRAINSTools-build/ITKv4-build/fftwd/src/fftw-3.3.4.tar.gz` and try again. The download failed at some point (random network error), but the file was created anyway because CMake doesn't do atomic downloads. It also doesn't try again when it sees a matching name on disk even if the hash is wrong.

**Comment by pnlbwh** [comment]
It's something to do with the download step because it occurs every time I make a new build, as well as when I delete fftw-3.3.4.tar.gz.  What command is being used to download the file?  Also maybe https has something to do with it.

**Comment by ihnorton** [comment]
I downloaded the URL w/ browser and the hash matches, so the file is correct on the server.

> What command is being used to download the file?
https://cmake.org/cmake/help/v3.4/command/file.html

> Also maybe https has something to do with it.
You do need to have a cmake built with ssl support [1](http://slicer-devel.65872.n3.nabble.com/Problems-building-Slicer-in-Ubuntu-14-04-3-LTS-Download-problem-using-https-in-make-cmake-td4035936.html), but the download should fail immediately with a different error if that is not the case.

**Comment by reckbo** [comment]
I tried it on my home network and it builds fine, so it must have something to do with the PNL/Partners network.

**Comment by hjmjohnson** [comment]
It seems that this was an environmental configuration problem.  Closing unless more information is provided.
