### ISSUE TITLE
DWIConvert: Conversion to FSL doesn't produce bvec/bval files

### ISSUE THREAD

**Issue by reckbo** [BRAINSia/BRAINSTools#270]
I have two sets of DWI scans for a patient, and running DWIConvert on them produces bvec/bval
files for one but not the other.  Converting to nrrd works fine for both sets.  Converting from nrrd to fsl
says I need input bvec/bval files, but those are exactly what I'm trying to generate.

Any hint on what the problem may be?

**Comment by hjmjohnson** [comment]
We would need to debug the program and reproduce the problem locally.  We have not run into this issue in the past.

Hans

**Comment by ihnorton** [comment]
@reckbo do you get any error messages on the command line or the Slicer log view?

Are you able to share them locally? If so I can take a look.

**Comment by hjmjohnson** [comment]
We don’t use DWIConvert in the slicer environment.  I am not sure which version is being used there. 

I would recommend trying the latest source build.

Hans

**Comment by reckbo** [comment]
This was my mistake, I was missing the '--conversionMode DicomToFSL' flag.  Without it the app just generates a nifti volume.
