### ISSUE TITLE
Release tarballs are missing Cmake version file

### ISSUE THREAD

**Issue by reckbo** [BRAINSia/BRAINSTools#289]
The release archive at

    https://github.com/BRAINSia/BRAINSTools/archive/v4.7.0.tar.gz

fails to build because it's missing `BRAINSTools-4.7.0/CMake/ProjectSourceVersionVars.cmake`,
which according to the comments is supposed to be set with the appropriate versioning information in a release tarball (it looks for this file when there is no .git directory).

I checked and `v4.6.0.tar.gz` is also missing this file.

**Comment by hjmjohnson** [comment]
@reckbo How did you find that file?  It must be automatically created by Github.  

If you know how to fix this, we would be happy to have a pull request.

Hans

**Comment by reckbo** [comment]
I would but I don't think I can modify your tarballs? Heres' the file that needs to be added to https://github.com/BRAINSia/BRAINSTools/archive/v4.7.0.tar.gz:

CMake/ProjectSourceVersionVars.cmake:
```
macro( _set_if_not_empty var value )
  if( NOT "${value}" STREQUAL "" )
    set( ${var} "${value}" )
  endif()
endmacro()

set( _GIT_VERSION_MAJOR "4" )
set( _GIT_VERSION_MINOR "7" )
_set_if_not_empty( _GIT_VERSION_PATCH "0" )
_set_if_not_empty( _GIT_VERSION_TWEAK "" )
_set_if_not_empty( _GIT_VERSION_RC "" )
_set_if_not_empty( _GIT_VERSION_POST "" )
_set_if_not_empty( _GIT_VERSION_DEV "84" )
_set_if_not_empty( _GIT_VERSION_HASH "0a128" )
```

I'm using your tarball to add BRAINSTools to a package manager, so by fixing this issue means I don't have to manually patch it.

**Comment by hjmjohnson** [comment]
@recbo  Those tarball files are not maintained.  They are part of the github api.  The http url dynamically creates the tarball from the git repository for the given tag.


You could provide a patch and create a 4.7.1 release  

git clone << BRAINTools >>
git checkout v4.7.0 -b FixForv470
<< make patches >>  << change minor version number >>
git push origin FixForv470:FixForv470
<< make pull request>>

**Comment by hjmjohnson** [comment]
@reckbo There should now be a 4.7.1 release that I hope works.

**Comment by reckbo** [comment]
@hjmjohnson Thanks! It compiles without error.

Soon nix users will be able to install it by

    nix-env -i BRAINSTools
