### ISSUE TITLE
BCD --inputLandmarksEMSP file format

### ISSUE THREAD

**Issue by reginakim** [BRAINSia/BRAINSTools#306]
@hjmjohnson @aghayoor 
The inputLandmarksEMSP file provides convenient work around when BCD failed for eye detection. While it provides a good and quick way to fix eye using 3DSlicer, the format can be improved further.

Currently, the BCD fails if '--inputLandmarksEMSP' looks as:
    # Markups fiducial file version = 4.3                                                                                                                            
    # CoordinateSystem = 0
    # columns = id,x,y,z,ow,ox,oy,oz,vis,sel,lock,label,desc,associatedNodeID
    vtkMRMLMarkupsFiducialNode_0,31.7664,71.4745,0.5,0,0,0,1,1,1,0,LE,,
    vtkMRMLMarkupsFiducialNode_1,-26.1606,74.2774,0.5,0,0,0,1,1,1,0,RE,,

but works with following (if the line starts with the landmark name):
    # Markups fiducial file version = 4.3                                                                                                                            
    # CoordinateSystem = 0
    # columns = id,x,y,z,ow,ox,oy,oz,vis,sel,lock,label,desc,associatedNodeID
    LE,31.7664,71.4745,0.5,0,0,0,1,1,1,0,LE,,
    RE,-26.1606,74.2774,0.5,0,0,0,1,1,1,0,RE,,
~                                                                                                                                        
we may want to lookup both 'id' and 'associatedNodeID', since 3D Slicer saves fcsv like the first one. 

Just opinion. Just let me know.

**Comment by hjmjohnson** [comment]
Slicer has changed their format so many times in the past few years.  It is hard to keep up.  It would be WONDERFUL to have this represented properly again.

**Comment by hjmjohnson** [comment]
We are probably not going to fix this.
