### ISSUE TITLE
DWIConvert Default Data Model

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/BRAINSTools#323]
Hui,

Please change the default data model for DWIConvert from a "Unwrapped3DVolume" to a 3DVectorVolume format.  

Move the DICOM only Unwrapped3DVolume representation to the DICOM subclass of DWIConvert so that it does not contaminate the default exposed API.

Hans

**Comment by Hui-Xie** [comment]
Changing into 3DVectorVolume involves changing of infrastructure data structure, and all test tool program. I tried it, and failed. It is a huge work. Now we keep its current data structure.
