### ISSUE TITLE
Psuedo-code for converting VectorVolumeTo4DVolume

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/BRAINSTools#325]
Hui,

You will need code similar to the following as well.

static Volume4DType::Pointer CreateEmpty4DVolume(VectorVolumeType::Pointer & inputVol)
{
  VectorVolumeType::SizeType inputSize =
    inputVol->GetLargestPossibleRegion().GetSize();
  VectorVolumeType::SpacingType   inputSpacing = inputVol->GetSpacing();
  VectorVolumeType::PointType     inputOrigin = inputVol->GetOrigin();
  VectorVolumeType::DirectionType inputDirection = inputVol->GetDirection();

  Volume4DType::Pointer FourDVolume = Volume4DType::New();
  Volume4DType::SizeType      volSize;
  Volume4DType::SpacingType   volSpacing;
  Volume4DType::PointType     volOrigin;
  Volume4DType::DirectionType volDirection;

  for( unsigned int i = 0; i < 3; ++i )
  {
    volSize[i] = inputSize[i];
    volSpacing[i] = inputSpacing[i];
    volOrigin[i] = inputOrigin[i];
    for( unsigned int j = 0; j < 3; ++j )
    {
      volDirection[i][j] = inputDirection[i][j];
    }
    volDirection[3][i] = 0.0;
    volDirection[i][3] = 0.0;
  }
  volDirection[3][3] = 1.0;
  volSpacing[3] = 1.0;
  volOrigin[3] = 0.0;
  volSize[3] = inputVol->GetNumberOfComponentsPerPixel();

  FourDVolume->SetRegions(volSize);
  FourDVolume->SetOrigin(volOrigin);
  FourDVolume->SetSpacing(volSpacing);
  FourDVolume->SetDirection(volDirection);
  FourDVolume->Allocate();
  return FourDVolume;
}

Volume4DType::Pointer Convert3DVectorVolumeTo4DVolume(VectorVolumeType::Pointer inputVol)
{
  Volume4DType::Pointer                         FourDVolume = CreateEmpty4DVolume(inputVol);
  const VectorVolumeType::SizeType              inputSize( inputVol->GetLargestPossibleRegion().GetSize() );
  const Volume4DType::IndexType::IndexValueType vecLength = inputVol->GetNumberOfComponentsPerPixel();

  VectorVolumeType::IndexType vecIndex;
  Volume4DType::IndexType     volIndex;
// convert from vector image to 4D volume image
  for( volIndex[3] = 0; volIndex[3] < vecLength; ++volIndex[3] )
  {
    for( volIndex[2] = 0; volIndex[2] < static_cast<Volume4DType::IndexType::IndexValueType>( inputSize[2] ); ++volIndex[2] )
    {
      vecIndex[2] = volIndex[2];
      for( volIndex[1] = 0; volIndex[1] < static_cast<Volume4DType::IndexType::IndexValueType>( inputSize[1] ); ++volIndex[1] )
      {
        vecIndex[1] = volIndex[1];
        for( volIndex[0] = 0; volIndex[0] < static_cast<Volume4DType::IndexType::IndexValueType>( inputSize[0] ); ++volIndex[0] )
        {
          vecIndex[0] = volIndex[0];
          FourDVolume->SetPixel(volIndex, inputVol->GetPixel(vecIndex)[volIndex[3]]);
        }
      }
    }
  }
  return FourDVolume;
}

**Comment by Hui-Xie** [comment]
Cancel the Convert task as the it involves huge changes in DWI infrastructure and test infrastructure.

**Comment by hjmjohnson** [comment]
This is needed, even if it involves huge changes.

**Comment by hjmjohnson** [comment]
@Hui-Xie Hui,  you need to complete the refactoring of the DWI before spring break 2018.  Both this project and the Intel speedup project must be completed before you can focus on a research project for your dissertation.

**Comment by hjmjohnson** [comment]
Abandoned project.
