### ISSUE TITLE
DWIConvert segfaults with no args

### ISSUE THREAD

**Issue by ihnorton** [BRAINSia/BRAINSTools#329]
on master.

```
31-36-129:BRAINSTools-build inorton$ ./bin/DWIConvert
======= DWI Convert Public Lib Ctest =========
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
Abort trap: 6
```
debugger:
```
(lldb) up
frame #11: 0x00000001001d981a DWIConvert`DWIConvert::findFilenameExt(this=0x00007fff5fbf3b38, filename=std::__1::string at 0x00007fff5fbf12f8) + 1242 at DWIConvertLib.cxx:339
   336 	//{ ".nii", ".nii.gz", ".nhdr", ".nrrd"}
   337 	std::string DWIConvert::findFilenameExt(const std::string filename){
   338 	    std::string::size_type pos = filename.rfind(".");
-> 339 	    std::string subStr = filename.substr(pos);
   340 	    if (".gz" == subStr){
   341 	        subStr = filename.substr(pos-4,4);
   342 	    }
(lldb) p pos
(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::size_type) $5 = 18446744073709551615
```

**Comment by Hui-Xie** [comment]
Isaiah, 

Thank You very much for helping me find this bug.
I modified the code like below. 
The reason that I didn't use existing method GetFileNameExtension is that I need to judge .nii instead of .gz in "filenname.nii.gz" input.

The latest code will be merged into master through a new pullrequest from ChangeDWIConvertDataModel branch in a few days.

Thank you very much again, and happy new year.

Modified code:
===============
//{ ".nii", ".nii.gz", ".nhdr", ".nrrd"}
std::string DWIConvert::findFilenameExt(const std::string filename){
    std::string subStr = "";
    std::string::size_type pos = filename.rfind(".");
    **_if (std::string::npos == pos){
        std::cerr<<"Error: incorrect filename to seek extention name. "<< std::endl;
        return subStr;
    }_**
    subStr = filename.substr(pos);
    if (".gz" == subStr){
        subStr = filename.substr(pos-4,4);
    }
    return subStr;
}

Thank you very much again.

**Comment by ihnorton** [comment]
A couple suggestions:
- it is better not to print minor errors in a utility function. Handle failures in the caller, if needed.
- don't make assumptions about positions/lengths when taking substrings.
- it might be better to replace [these lines]() with
```
inputExt = GetFileNameExtension(f)
if (inputExt.rfind("nii") != std::string::npos... 
```
for each pair check, rather than guessing about extensions in your find function (for example, someone might have their own naming convention like: `image.reg.nii.gz`)

> The reason that I didn't use existing method GetFileNameExtension is that I need to judge .nii instead of .gz in "filenname.nii.gz" input.

https://github.com/Kitware/VTK/blob/0fbc5276551f419bd70ddbf8ca35ca018ea70000/Utilities/KWSys/vtksys/SystemTools.cxx#L3847-L3860

**Comment by Hui-Xie** [comment]
Isaiah, 

Thank you very much. I like all your suggestions. I really appreciate you spending time reading my codes.

Yes. itksys::SystemTools::GetFilenameExtension() has better implement than mine, and which supports the subtle difference between Unix and Win32. 

**I followed your suggestions, and revised code like below:**

//currently supported file types: { ".nii", ".nii.gz", ".nhdr", ".nrrd"}
void DWIConvert::setInputFileType(const std::string& inputVolume, const std::string& inputDicomDirectory){
  m_inputVolume = inputVolume;
  m_inputDicomDirectory = inputDicomDirectory;
  if ("" == m_inputDicomDirectory && "" != m_inputVolume){
    **std::string inputExt = itksys::SystemTools::GetFilenameExtension(m_inputVolume);
    if ( std::string::npos != inputExt.rfind(".nii")) m_inputFileType = "FSL";
    else if (std::string::npos != inputExt.rfind(".nrrd") || std::string::npos != inputExt.rfind(".nhdr"))** m_inputFileType = "Nrrd";
    else {
      std::cerr <<"Error: file type of inputVoume is not supported currently"<<std::endl;
    }
  }
  else if ("" != m_inputDicomDirectory)
  {
    m_inputFileType = "Dicom";
  }
  else{
    std::cerr <<"Error: One of inputVoume and inputDicomDirectory must be empty string"<<std::endl;
  }
}

void DWIConvert::setOutputFileType(const std::string& outputVolume){
  m_outputVolume = outputVolume;
  **std::string outputExt = itksys::SystemTools::GetFilenameExtension(m_outputVolume);
  if (std::string::npos != outputExt.rfind(".nii")) m_outputFileType = "FSL";
  else if (std::string::npos != outputExt.rfind(".nrrd")|| std::string::npos != outputExt.rfind(".nhdr"))** m_outputFileType = "Nrrd";
  else{
    std::cerr <<"Error: the output file type is not supported currently"<<std::endl;
  }
}

Latest change have been pushed into ChangeDWIConvertDataModel branch, and will merge into master  in a few days.

Thank you very much again.
