### ISSUE TITLE
DWIConvert FSLToNrrd doesn't scale gradient vectors

### ISSUE THREAD

**Issue by reckbo** [BRAINSia/BRAINSTools#331]
DWIConvert in commit e13c873 doesn't scale the gradient vectors correctly when converting FSL to Nrrd.

```
DWIConvert --conversionMode FSLToNrrd --inputBVectors Dwi-\(DwiHcp-\(98\,99\)\,1004anon\).bvec --inputBValues Dwi-\(DwiHcp-\(98\,99\)\,1004anon\).bval --inputVolume      Dwi-\(DwiHcp-\(98\,99\)\,1004anon\).nii.gz -o /tmp/x.nrrd 

Scale Factor for Multiple BValues: 0 -- sqrt( 3010 / 3010 ) = 1
Scale Factor for Multiple BValues: 1 -- sqrt( 3010 / 3010 ) = 1
Scale Factor for Multiple BValues: 2 -- sqrt( 3010 / 3010 ) = 1
Scale Factor for Multiple BValues: 3 -- sqrt( 3010 / 3010 ) = 1
Scale Factor for Multiple BValues: 4 -- sqrt( 3010 / 3010 ) = 1
Scale Factor for Multiple BValues: 5 -- sqrt( 3010 / 3010 ) = 1
Scale Factor for Multiple BValues: 6 -- sqrt( 3010 / 3010 ) = 1
Scale Factor for Multiple BValues: 7 -- sqrt( 3010 / 3010 ) = 1
Scale Factor for Multiple BValues: 8 -- sqrt( 3010 / 3010 ) = 1
...
```

B-values are: 5 5 1490 2990 1495 ... etc.

The resulting DWI nrrd has gradient directions identical to the the bvec file.

**Comment by Hui-Xie** [comment]
Thank you Reckbo for pointing out the issue.
I will look into it on Thursday and try to fix it as soon as possible.
Happy new year,

**Comment by hjmjohnson** [comment]
Do you have a multi-shell data set that you could share with us for testing?  Preferably a de-identified dicom file.

 

We do not have any multi-shell data for testing.

 

Hans

**Comment by reckbo** [comment]
I can give you the nifti file, what's the best way to get it to you?

**Comment by hjmjohnson** [comment]
A dropbox link?

 

Thanks,

Hans

 

 

--

**Comment by hjmjohnson** [comment]
@Hui-Xie  Hui,  You stated that have a bug fix for this.  Please make a pull-request with referencing this issue when it is ready for distribution.

You need to add a test case to ensure that multi-shell always works.

Hans
