### ISSUE TITLE
Building BRAINSTools

### ISSUE THREAD

**Issue by crossmanith** [BRAINSia/BRAINSTools#349]
I'm trying to build BRAINSTools with enabled USE_SYSTEM_* flags. But instead of using the precompiled packages (ITK, DCMTK etc.) the build process downloads every package and starts to build it. Any hint how to change this behaviour?

Regards,
Christina Rossmanith

Dept. of Neurology
University Medicine Mannheim
University of Heidelberg

**Comment by hjmjohnson** [comment]
@crossmanith We have not had the time to properly implement the "USE_SYSTEM_*" flags.  We would be happy to accept a patch set from you if you can make this work.
