### ISSUE TITLE
Improve error message on missing tags->fallback to generic->failure

### ISSUE THREAD

**Issue by ihnorton** [BRAINSia/BRAINSTools#361]
There is a [discussion and example data](https://discourse.slicer.org/t/dwi-loading-from-dicom/1746) on the Slicer forum where some data (I think Siemens originally) fails to convert due to missing tags from aggressive anonymization. DWIConvert falls back to the generic reader, which also fails. The error shown could be more informative:

```
Diffusion-weighted DICOM Import (DWIConvert) standard error:

Exception creating converter 
itk::ExceptionObject (00000070D358D430)
Location: "unknown" 
File: D:\D\P\Slicer-481-package\BRAINSTools\DWIConvert\GenericDWIConverter.cxx
Line: 13
Description: itk::ERROR:  LoadFromDisk not relevant
```

Ideally DWIConvert could give some descriptive information rather than the exception, and maybe hints/suggestions about common causes of errors (missing tags, anonymization, etc.)

**Comment by hjmjohnson** [comment]
Thanks.  I'll be happy to incorporate a pull request for this.  

Closing:  Backlog_ideas_for_improvement ideas will be reviewed from the closed issues list as time permits.
