### ISSUE TITLE
Review population based template building.

### ISSUE THREAD

**Issue by hjmjohnson** [BRAINSia/BRAINSTools#405]
@reginakim Are these changes worth preserving and incorporating into BRAINSTools?

https://github.com/BRAINSia/BRAINSTools/commits/popTemp2

**Comment by reginakim** [comment]
Hans, 

Let's discard the change and close the issue. The project was pursued to make the code 'useful' for a certain case, but I think the group-wise template generating could be done using population template generation. In addition, the code has been evolved continuously, the effort to make this code work may not worth it. 

Thank you for heads-up. 

Regina

**Comment by hjmjohnson** [comment]
@reginakim Thanks.  Just making sure.  Feel free to close any other branches that you made that you think are outdated/not worth updating.  

There were 56 branches originally, and I'd like to get it down to 10 or so.
