### ISSUE TITLE
Bug: inputLandmarkFiles.size() >= 2 instead of >2 ?

### ISSUE THREAD

**Issue by reginakim** [BRAINSia/BRAINSTools#442]
@hjmjohnson 

https://github.com/BRAINSia/BRAINSTools/blob/e4dd4e38e16c7cd1e358495cc04ab26ecb08c271/BRAINSConstellationDetector/landmarkStatistics/GenerateAverageLmkFile.cxx#L49

I think this is typo. Current way (inputLandmarkFiles.size() >2) will skip if the number of landmark files given is exactly two. Throwing error: 
 "ERROR: No input file name is defined"

Please confirm and update. :) 

Regina

**Comment by hjmjohnson** [comment]
Please provide a PR and I will approve very quickly.  I think you are correct.

**Comment by hjmjohnson** [comment]
Resolved last year.
