### ISSUE TITLE
BCD: Error during Reading in external files

### ISSUE THREAD

**Issue by Qasim-Latrobe** [BRAINSia/BRAINSTools#461]
## *Who* is the bug affecting?
The BCD doesn't run.

## *What* is affected by this bug?
The error doesn't allow BCD to run at all.

## *When* does this occur?
Whenever I try to run BCD.

## *Where* on the platform does it happen?
Ubuntu command line.

## *How* do we replicate the issue?
1) Install Ubuntu shell on windows 10.
2) Build BRAINSTools as described by Readme Document.
3) Run BCD as bash for re-aligning MRI anatomical image. 

## Expected behavior (i.e. solution)
The program should create a re-aligned image file.

## The Error Log is given below:
Reading in external files...
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 0:
  #000: /mnt/c/Users/19830112/downloads/build/ITKv5/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5F.c line 509 in itk_H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: /mnt/c/Users/19830112/downloads/build/ITKv5/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 1400 in itk_H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: /mnt/c/Users/19830112/downloads/build/ITKv5/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 1546 in itk_H5F_open(): unable to open file: time = Wed Dec 18 11:53:38 2019
, name = '/mnt/c/Users/19830112/downloads/build/BRAINSTools-Release-EPRelease-build/bin/LLSModel.h5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #003: /mnt/c/Users/19830112/downloads/build/ITKv5/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FD.c line 734 in itk_H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #004: /mnt/c/Users/19830112/downloads/build/ITKv5/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = '/mnt/c/Users/19830112/downloads/build/BRAINSTools-Release-EPRelease-build/bin/LLSModel.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 0:
  #000: /mnt/c/Users/19830112/downloads/build/ITKv5/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5F.c line 509 in itk_H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: /mnt/c/Users/19830112/downloads/build/ITKv5/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 1400 in itk_H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: /mnt/c/Users/19830112/downloads/build/ITKv5/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 1546 in itk_H5F_open(): unable to open file: time = Wed Dec 18 11:53:38 2019
, name = '/mnt/c/Users/19830112/downloads/build/BRAINSTools-Release-EPRelease-build/bin/LLSModel.h5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #003: /mnt/c/Users/19830112/downloads/build/ITKv5/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FD.c line 734 in itk_H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #004: /mnt/c/Users/19830112/downloads/build/ITKv5/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = '/mnt/c/Users/19830112/downloads/build/BRAINSTools-Release-EPRelease-build/bin/LLSModel.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
Error reading LLS Model

![Error](https://user-images.githubusercontent.com/56423320/71146210-6d190e80-2278-11ea-9d4e-69e0c24da850.png)

**Comment by hjmjohnson** [comment]
BCD has undergone significant fixes and easier installation over the past few months.  Please retry.
