### ISSUE TITLE
GTRACT command line Slicer 4.10.

### ISSUE THREAD

**Issue by Adam123-png** [BRAINSia/BRAINSTools#465]
Hello all,

I want to run GTRACT tools in the 3D Slicer 4.10.2. app on Windows 10. I already downloaded the GTRACT folder but now I don´t know where to put the GTRACT folder in order to start using GTRACT tools. 

Slicer.exe is here: C:\Program Files\Slicer 4.10.2. Should I put GTRACT folder here: C:\Program Files\Slicer 4.10.2\lib\Slicer-4.10\cli-modules where other Slicer tools are placed?

How can I invoke one GTRACT tool through command line?

Thanks a lot
Regards
Adam

**Comment by hjmjohnson** [comment]
GTRACT is primarily a command line tool.  I don't know what you mean by "downloaded the GTRACT folder".  It is a C++ program that requires compiling to generate the binaries.  It sounds like perhaps you did not compile the BRAINSTools package.
