### ISSUE TITLE
problems with installation

### ISSUE THREAD

**Issue by s2334** [BRAINSia/BRAINSTools#527]
I'm running ubuntu and I'm trying to install BRAINSTools.  I followed the instructions:
```

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git python2.7
python2.7-dev g++ freeglut3-dev
```

And got the error "python2.7-dev: command not found."
I ignored the last step and continued with:

```
URL=http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
wget ${URL}
# Decompress the file
tar -xzvf cmake-3.2.1-Linux-x86_64.tar.gz
# Add the binary to your PATH environment variable
export PATH=${PWD}/cmake-3.2.1-Linux-x86_64/bin:${PATH}

```
This ran without issues but then:

```
git clone https://github.com/BRAINSia/BRAINSTools.git
mkdir build
cd build
CC=/usr/bin/gcc-4.8 \
CXX=/usr/bin/g++-4.8 \
cmake ../BRAINSTools \
make -j${NUMOFTHREADS} -k
```

I got the error 
```
CMake Error: The source directory "/home/s2334/build/-k" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

Can someone help me please?

**Comment by oguzcanbekar** [comment]
Hi could you find the solution for this situation?

**Comment by hjmjohnson** [comment]
It appears that your environmental variable ${NUMOFTHREADS} is not set properly. 

You should run the commands one at a time, and diagnose each problem separately.

The newline between "python" and "python-dev" needs to be removed, or you need to run `apt-get` to install each package separately.  

You may want to ask your system administrator, or someone with unix experience to help you.
