### ISSUE TITLE
Siemens Sonata DWIConvert issue from slicer-users list

### ISSUE THREAD

**Issue by pieper** [BRAINSia/BRAINSTools#76]
---------- Forwarded message ----------
From: uhlich uhlich@ualberta.ca
Date: Fri, Oct 18, 2013 at 12:34 PM
Subject: [slicer-users] Siemens Sonata DWIConvert Issue
To: slicer-users@bwh.harvard.edu

Hi all,
Thanks to afe in the last thread, I know how to use DWIConvert on CentOS
now.

Interestingly, it still has a small issue that I had run up against a few
times while using DicomToNrrdConverter on my Windows machine on large
amounts of data. I have been converting MRI volumes from Dicom series to
NRRD and the issue (I believed at the time) was with non-square MRI images.
Everytime I input an MRI volume containing non-square slices,
DicomToNrrdConverter would hang indefinitely. I couldn't figure it out so I
just stopped trying on non-square volumes (there were a relatively small
number of them in my dataset).

Skip ahead a while and now I am using DWIConvert and finding the same
problem. Only since then I've been made aware of a Siemens issue, and the
use of --useBMatrixGradientDirections to recompute erroneous vector
coordinates. It was then that I realized that most of these non-square
volumes (if not all) are from Siemens. So I tried that flag thinking
everything was solved, but it still didn't work. What follows is hopefully
relevant data from a particular example.

Size of the volume = 512 x 416 x 19

Manufacturer: 'SIEMENS'
ManufacturerModelName: 'Sonata'

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Command Line Arguments
    conversionMode: DicomToNrrd
    inputVolume:
    outputVolume: TestsDir3/Vol.nrrd
    fMRIOutput: 0
    inputDicomDirectory: CR00491/2002-06-17/T1C/raw
    outputDirectory: .
    gradientVectorFile:
    smallGradientThreshold: 0.2
    writeProtocolGradientsFile: 0
    useIdentityMeaseurementFrame: 0
    useBMatrixGradientDirections: 1
    inputBValues:
    inputBVectors:
    outputBValues:
    outputBVectors:
    echoSwitch: 1
    xmlSwitch: 0
    processInformationAddressString: 0
    returnParameterFile:
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (8b1f,0008) is odd
E: DcmElement: Unknown Tag & Data (8b1f,0008) larger (1297806941) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
W: DcmItem: Length of element (5089,474e) is odd
E: DcmElement: Unknown Tag & Data (5089,474e) larger (169478669) than
remaining bytes in file
=================== this->m_SlicesPerVolume:19
Dicom images are ordered in a volume interleaving way.
ImageOrientationPatient (0020:0037): LPS Orientation Matrix
0.999328 1.33802e-10 -0.0366437
-0.00287503 0.996917 -0.0784064
0.0365308 0.0784591 0.996248

this->m_SpacingMatrix
0.429688 0 0
0 0.429688 0
0 0 5

NRRDSpaceDirection
0.429399 5.74932e-11 -0.183219
-0.00123537 0.428363 -0.392032
0.0156968 0.0337129 4.98124

Slice 0: -93.7762 -122.603 -98.8518
Slice 1: -94.0511 -123.191 -91.3799
Slice order is IS
Warning: Cannot find complete information on B_value in 0029|1010
/home/uhlich/BadRegistrationTests/CR00491/2002-06-17/T1C/raw/Image001.dcm
has no non-zero diffusion vectors
Exception extracting gradient vectors
itk::ExceptionObject (0x250d810)
Location: "unknown"
File:
/home/kitware/Dashboards/Package/Slicer-431-package/BRAINSTools/DWIConvert/SiemensDWIConverter.h
Line: 294
Description: itk::ERROR:

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by ihnorton** [comment]
The issue here appears to be that the CSA header tag is missing, so `ExtractDWIData` throws when it doesn't find that tag. I have some single slice (not mosaic) phantom data that fails with the same error, but works fine with dcm2nii -- I believe it falls back to `(0x0019, 0x100e)` where the gradient information is available. Interestingly, the newer dcm2niix also fails on this dataset, but has some commented-out definitions to look at that field (perhaps it didn't make it into the port from pascal yet). I'm working on a patch, and trying to get permission to release the data publicly to add as a regression test.
